/**
 * CesiumViewer.tsx — Core CesiumJS globe component.
 *
 * Mounts the Cesium Viewer into a full-screen div, loads GeoJSON data layers,
 * handles click picking, and exposes imperative controls via ref.
 */

import { useEffect, useRef, useCallback, forwardRef, useImperativeHandle } from "react";
import * as Cesium from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import type { FilterState, SelectedFeature } from "@/types";
import { loadGeoJSON, removeLayer, pickFeature, type LoadedLayer } from "@/lib/dataLoader";

// ─── Public imperative handle ─────────────────────────────────────────────────

export interface CesiumViewerHandle {
  zoomToRegion: (region: string) => void;
  zoomToFeature: (lon: number, lat: number) => void;
  set3DMode: (is3D: boolean) => void;
  setUnderground: (enabled: boolean) => void;
  reloadLayers: () => void;
}

// ─── Region bounding rectangles ───────────────────────────────────────────────

const REGION_RECTS: Record<string, Cesium.Rectangle> = {
  africa:       Cesium.Rectangle.fromDegrees(-20, -35,  55,  38),
  americas:     Cesium.Rectangle.fromDegrees(-82, -56, -34,  72),
  europe:       Cesium.Rectangle.fromDegrees(-12,  34,  42,  72),
  "asia-pacific": Cesium.Rectangle.fromDegrees(25, -10, 155,  55),
  "middle-east":  Cesium.Rectangle.fromDegrees(32,  12,  63,  42),
  global:       Cesium.Rectangle.fromDegrees(-180, -85, 180,  85),
};

// ─── Dataset files to load ───────────────────────────────────────────────────
// Load merged global outputs from the ETL pipeline.  Fall back to per-source
// files so the map still works when only seed data is present.

const DATA_FILES = [
  // Merged outputs (generated by merge.py — contain all sources combined)
  "./data/spans-global.geojson",
  "./data/nodes-global.geojson",
];

// ─── Props ────────────────────────────────────────────────────────────────────

interface Props {
  filters: FilterState;
  showSpans: boolean;
  showNodes: boolean;
  onFeatureSelect: (feature: SelectedFeature | null) => void;
  onFeatureHover?: (feature: SelectedFeature | null, x: number, y: number) => void;
  cesiumIonToken?: string;
  googleMapsApiKey?: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

const CesiumViewer = forwardRef<CesiumViewerHandle, Props>(function CesiumViewer(
  { filters, showSpans, showNodes, onFeatureSelect, onFeatureHover, cesiumIonToken, googleMapsApiKey },
  ref
) {
  const containerRef = useRef<HTMLDivElement>(null);
  const viewerRef    = useRef<Cesium.Viewer | null>(null);
  const layersRef    = useRef<LoadedLayer[]>([]);
  const handlerRef   = useRef<Cesium.ScreenSpaceEventHandler | null>(null);

  // ─── Imperative API ──────────────────────────────────────────────────────

  useImperativeHandle(ref, () => ({
    zoomToRegion(region: string) {
      if (!viewerRef.current) return;
      const rect = REGION_RECTS[region] ?? REGION_RECTS["global"];
      viewerRef.current.camera.flyTo({ destination: rect, duration: 1.5 });
    },
    zoomToFeature(lon: number, lat: number) {
      if (!viewerRef.current) return;
      viewerRef.current.camera.flyTo({
        destination: Cesium.Cartesian3.fromDegrees(lon, lat, 500_000),
        duration: 1.2,
      });
    },
    set3DMode(is3D: boolean) {
      if (!viewerRef.current) return;
      if (is3D) viewerRef.current.scene.morphTo3D(0.5);
      else       viewerRef.current.scene.morphTo2D(0.5);
    },
    setUnderground(enabled: boolean) {
      if (!viewerRef.current) return;
      const globe = viewerRef.current.scene.globe;
      globe.translucency.enabled = enabled;
      globe.translucency.frontFaceAlpha = enabled ? 0.4 : 1.0;
      // undergroundColor accepts Color; just reset to default dark when off
      globe.undergroundColor = Cesium.Color.fromCssColorString(
        enabled ? "#0a0a1a" : "#000014"
      );
    },
    reloadLayers() {
      reloadAllLayers();
    },
  }));

  // ─── Layer reload ─────────────────────────────────────────────────────────

  // Minor nodes (DC, PoP) shown only when camera is closer than this altitude
  const MINOR_NODE_ALTITUDE = 1_500_000; // 1500 km

  const applyAltitudeVisibility = useCallback(() => {
    const viewer = viewerRef.current;
    if (!viewer) return;
    const altitude = viewer.camera.positionCartographic.height;
    const showMinor = showNodes && altitude < MINOR_NODE_ALTITUDE;
    for (const layer of layersRef.current) {
      layer.billboardsMinor.show = showMinor;
    }
  }, [showNodes]);

  const reloadAllLayers = useCallback(async () => {
    const viewer = viewerRef.current;
    if (!viewer) return;

    for (const layer of layersRef.current) {
      removeLayer(viewer.scene, layer);
    }
    layersRef.current = [];

    const results = await Promise.allSettled(
      DATA_FILES.map((url) => loadGeoJSON(viewer.scene, url, filters))
    );

    const altitude = viewer.camera.positionCartographic.height;
    const showMinor = showNodes && altitude < MINOR_NODE_ALTITUDE;

    for (const result of results) {
      if (result.status === "fulfilled") {
        const layer = result.value;
        layer.polylines.show       = showSpans;
        layer.billboards.show      = showNodes;
        layer.billboardsMinor.show = showMinor;
        layer.labels.show          = showNodes;
        layersRef.current.push(layer);
      } else {
        console.warn("Layer load failed:", result.reason);
      }
    }
  }, [filters, showSpans, showNodes, applyAltitudeVisibility]);

  // ─── Mount Cesium Viewer (once) ───────────────────────────────────────────

  useEffect(() => {
    if (!containerRef.current || viewerRef.current) return;

    Cesium.Ion.defaultAccessToken = cesiumIonToken ?? "";

    let cancelled = false;
    // Holds cleanup refs so the return fn can teardown even if init is in-flight
    let cleanupFn: (() => void) | null = null;

    const osmLayer = () =>
      Cesium.ImageryLayer.fromProviderAsync(
        Promise.resolve(
          new Cesium.OpenStreetMapImageryProvider({
            url: "https://tile.openstreetmap.org/",
            credit: "© OpenStreetMap contributors",
          })
        )
      );

    const init = async () => {
      // Base imagery: try Google Maps, fall back to OSM on any error
      let baseLayer: Cesium.ImageryLayer;
      if (googleMapsApiKey) {
        try {
          Cesium.GoogleMaps.defaultApiKey = googleMapsApiKey;
          const provider = await Cesium.Google2DImageryProvider.fromUrl({
            mapType: "roadmap",
            key: googleMapsApiKey,
          });
          baseLayer = new Cesium.ImageryLayer(
            provider as unknown as Cesium.ImageryProvider
          );
        } catch (e) {
          console.warn("Google Maps base layer failed — falling back to OSM:", e);
          baseLayer = osmLayer();
        }
      } else {
        baseLayer = osmLayer();
      }

      if (cancelled || !containerRef.current) return;

      const viewer = new Cesium.Viewer(containerRef.current, {
        baseLayer,
        // Terrain: flat unless ion token given (async API in Cesium ≥1.110)
        terrain: cesiumIonToken
          ? Cesium.Terrain.fromWorldTerrain({ requestVertexNormals: true })
          : undefined,
        baseLayerPicker:       false,
        geocoder:              false,
        homeButton:            false,
        sceneModePicker:       false,
        navigationHelpButton:  false,
        animation:             false,
        timeline:              false,
        fullscreenButton:      false,
        vrButton:              false,
        infoBox:               false,
        selectionIndicator:    false,
        requestRenderMode:     false,
        maximumRenderTimeChange: Infinity,
        scene3DOnly:           false,
      });

      // Globe appearance
      viewer.scene.globe.enableLighting     = true;
      viewer.scene.globe.showGroundAtmosphere = true;
      if (viewer.scene.skyAtmosphere) {
        viewer.scene.skyAtmosphere.show = true;
      }

      // Dark space background
      viewer.scene.backgroundColor = Cesium.Color.fromCssColorString("#0a0a1a");

      // Start with a global view
      viewer.camera.flyTo({ destination: REGION_RECTS["global"], duration: 0 });

      viewerRef.current = viewer;

      // ── Click + hover pick handlers ────────────────────────────────────
      const handler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);

      handler.setInputAction(
        (movement: Cesium.ScreenSpaceEventHandler.PositionedEvent) => {
          const feature = pickFeature(viewer.scene, movement.position, layersRef.current);
          onFeatureSelect(feature);
        },
        Cesium.ScreenSpaceEventType.LEFT_CLICK
      );

      // Hover: throttled via rAF to avoid redundant picks mid-frame
      let hoverRaf = 0;
      handler.setInputAction(
        (movement: Cesium.ScreenSpaceEventHandler.MotionEvent) => {
          if (!onFeatureHover) return;
          cancelAnimationFrame(hoverRaf);
          const pos = movement.endPosition;
          hoverRaf = requestAnimationFrame(() => {
            const feature = pickFeature(viewer.scene, pos, layersRef.current);
            // Convert Cesium canvas coords to page coords
            const rect = (viewer.scene.canvas as HTMLCanvasElement).getBoundingClientRect();
            onFeatureHover(feature, rect.left + pos.x, rect.top + pos.y);
          });
        },
        Cesium.ScreenSpaceEventType.MOUSE_MOVE
      );

      handlerRef.current = handler;

      // ── Camera altitude → minor node visibility ────────────────────────
      // camera.moveEnd fires after every pan/zoom ends (more reliable than
      // camera.changed which only fires on >50% positional delta).
      const updateMinorVisibility = () => {
        const altitude = viewer.camera.positionCartographic.height;
        const showMinor = altitude < 1_500_000;
        for (const layer of layersRef.current) {
          layer.billboardsMinor.show = showMinor;
          // Also show labels for minor nodes when close enough
          layer.labels.show = altitude < 3_000_000;
        }
      };
      viewer.camera.moveEnd.addEventListener(updateMinorVisibility);

      cleanupFn = () => {
        handler.destroy();
        viewer.camera.moveEnd.removeEventListener(updateMinorVisibility);
        viewer.destroy();
        viewerRef.current = null;
      };

      // If the effect was cleaned up while we were awaiting, destroy immediately
      if (cancelled) cleanupFn();
    };

    init();

    return () => {
      cancelled = true;
      if (cleanupFn) {
        cleanupFn();
        cleanupFn = null;
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ─── Reload on filter/visibility change ──────────────────────────────────

  useEffect(() => {
    reloadAllLayers();
  }, [reloadAllLayers]);

  // ─── Sync span/node visibility without full reload ────────────────────────

  useEffect(() => {
    for (const layer of layersRef.current) layer.polylines.show = showSpans;
  }, [showSpans]);

  useEffect(() => {
    const altitude = viewerRef.current?.camera.positionCartographic.height ?? Infinity;
    const showMinor = showNodes && altitude < 1_500_000;
    for (const layer of layersRef.current) {
      layer.billboards.show      = showNodes;
      layer.billboardsMinor.show = showMinor;
      layer.labels.show          = showNodes;
    }
  }, [showNodes]);

  return (
    <div
      ref={containerRef}
      className="absolute inset-0 w-full h-full"
      style={{ background: "#0a0a1a" }}
    />
  );
});

export default CesiumViewer;
